#!/bin/bash
INIT_SQL_REQUEST="
  CREATE USER $POSTGRES_USER PASSWORD '$POSTGRES_PASSWORD';
  CREATE DATABASE $POSTGRES_DB;
  GRANT ALL PRIVILEGES ON DATABASE $POSTGRES_DB TO $POSTGRES_USER;
"
echo -n "$INIT_SQL_REQUEST" | psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB"
POSTGRES_PASSWORD="$POSTGRES_PASSWORD" psql -U "$POSTGRES_USER" -d "$POSTGRES_DB" -w -f "/sql/init.sql"