version: '3'

services:
  kuzzle:
    image: kuzzleio/howto-syncdata-kuzzle
    volumes:
      - "./plugin:/var/app/plugins/enabled/kuzzle-plugin-sync-cassandra"
      - "./scripts:/scripts"
    depends_on:
      - redis
      - elasticsearch
      - cassandra
    ports:
      - "7512:7512"
    environment:
      - kuzzle_services__db__client__host=http://elasticsearch:9200
      - kuzzle_services__internalCache__node__host=redis
      - kuzzle_services__memoryStorage__node__host=redis
      - kuzzle_server__maxRequestSize=1GB
      - kuzzle_limits__documentsWriteCount=100000
      - NODE_ENV=development
      - DEBUG=kuzzle:plugins

  redis:
    image: redis:3.2

  elasticsearch:
    image: kuzzleio/elasticsearch:5.4.1
    environment:
      - cluster.name=kuzzle
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"

  cassandra:
    image: kuzzleio/howto-syncdata-cassandra
    ports:
      - "9042:9042"
